version: '3.8'

services:
  fastapi:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://user:password@postgres/dbname
      - CHROMA_URL=http://chroma:8000

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - postgres_data:/var/lib/postgresql/data

  chroma:
    image: chromadb/chroma:latest
    restart: always
    ports:
      - "8000:8000"

volumes:
  postgres_data: